### ISSUE TITLE
Infinity loop

### ISSUE THREAD

**Issue by 0bvim** [willtrigo/42_push_swap#1]
With following inputs

```bash
./push_swap "1 2 -1 0 -2147483648"
./push_swap 1 2 -1 0 -2147483648
```

Advice:
When compile your program to pass it in tests, remove `-Ofast`  flag. In tests when you use this flag, the infinity loop does not core dump the program, so you can 'pass' in some cases that you does not pass in the test.

![image](https://github.com/user-attachments/assets/1450290c-200f-480d-8817-bd605edf96e4)
![image](https://github.com/user-attachments/assets/60979bcc-0bef-4551-84d2-3615abd4b4fb)

**Comment by 0bvim** [comment]
With any input that have `-2147483648` this problem happen.

**Comment by willtrigo** [comment]
the same error in both parts mandatory and bonus, thanks very much for the help =]
